/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsu.fpmi.edupract;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout.Group;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author SuerteMind
 */
public class NewJPanel extends javax.swing.JPanel {
     // Variables declaration - do not modify//GEN-BEGIN:variables
    public char key ='a';
    public String rbutton1;
    public String rbutton2;
    public String button1;
    public String label;
    public String STR = "Button choosen: nothing selected";
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton flag;
    private javax.swing.JLabel jLabel1;
    
    ActionListener listener = new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent ae) {
            
            STR = "Button choosen: ";
            if(jRadioButton1.isSelected())
                STR += " " + rbutton1 + " ";
            if(jRadioButton2.isSelected())
                STR += " " + rbutton2 + " ";
            
            if(!jRadioButton2.isSelected() && !jRadioButton1.isSelected())
                STR += " nothing selected ";
            
         
        }
    };

    private char c;

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        //setEnterKey("a");
        initEnterKey();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton(); 
        
        
        jRadioButton1.addActionListener(listener);
        jRadioButton1.setSelected(false);
        jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) { 
                jRadioButtonKeyTyped(evt);
            }
        });
        

        jRadioButton2 = new javax.swing.JRadioButton();
        
        jRadioButton2.addActionListener(listener);
        jRadioButton2.setSelected(false);
        
        jRadioButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) { 
                jRadioButtonKeyTyped(evt);
            }
        });
        
        
        //flag = new javax.swing.JRadioButton();
        //flag.addActionListener(listener);
        //flag.setSelected(false);
        
        //flag.addKeyListener(new java.awt.event.KeyAdapter() {
          //  public void keyTyped(java.awt.event.KeyEvent evt) { 
            //    jRadioButtonKeyTyped(evt);
            //}
        //});
        
        //ButtonGroup group = new ButtonGroup();
       // group.add(jRadioButton1);
       // group.add(jRadioButton2);
        
        setToolTipText("");

        jLabel1.setText(label);
        
        jRadioButton1.setText(rbutton1);
        //flag.setText("confirm");
        jRadioButton2.setText(rbutton2);

        jButton1.setText(button1);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                //.addGap(18, 18, 18)
                //.addComponent(flag) 
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    //.addComponent(flag)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jRadioButtonKeyTyped(java.awt.event.KeyEvent evt){
    if(evt.getKeyChar() == key){
        jButton1.doClick();
    }
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed 
        //if(flag.isSelected())
        JOptionPane.showMessageDialog(this, STR);
        //else
          //JOptionPane.showMessageDialog(this, "you not confirm your choice!");  
    }//GEN-LAST:event_jButton1ActionPerformed

    

    private void initEnterKey() {
        jButton1.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                if (e.getKeyChar() == c) {
                    jButton1.doClick();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    
    public void setRbutton1(String str)
    {
        rbutton1 = str;
        jRadioButton1.setText(str);
    }
    
    public String getrbutton1()
    {
        return jRadioButton1.getText();
    }
    
    public void setbutton1(String str)
    {
        button1 = str;
        jButton1.setText(str);
    }
    
    public String getbutton1()
    {
        return jButton1.getText();
    }
    
    public  void setRbutton2(String str)
    {
        rbutton2 = str;
        jRadioButton2.setText(str);
    }
    
    public String getrbutton2()
    {
        return jRadioButton2.getText();
    }
    
    public void setlabel(String str)
    {
        label = str;
        jLabel1.setText(str);
    }
    
    public String getlabel()
    {
        return jLabel1.getText();
    }
    
    public void setKey(char str)
    {
        key = str;
    }
    
    public char getKey()
    {
        return key;
    }
}


